### ISSUE TITLE
Logout Button throws an error

### ISSUE THREAD

**Issue by jaensen** [circlesland/o-platform#530]
Must be tested. Don't know the issue exactly at this point.

**Comment by codeho** [comment]
After testing, this is not an issue, as the 'i forgot..' link works just fine.
We figured what was probably meant here was a bug on 'Log out' on the transactions page, which is now fixed.

**Comment by samuelandert** [comment]
Reopend this one, still buggy
<img width="1440" alt="Bildschirmfoto 2021-11-26 um 21 26 19" src="https://user-images.githubusercontent.com/747161/143627128-266f8357-b888-4e25-98b5-8abf98018994.png">

**Comment by samuelandert** [comment]
Logout works in generell, but only after refresh
